#FROM python:3.8-slim
FROM golang:latest

MAINTAINER foo
WORKDIR /VTOT
WORKDIR $GOPATH/go
COPY . $GOPATH/go
COPY go.mod ./
COPY go.sum ./
COPY * ./


RUN apt-get update && \
    apt-get install vim -y

#RUN pip install aliyun-python-sdk-core==2.13.3 -i https://mirrors.aliyun.com/pypi/simple/ &&\
#    pip install requests &&\
RUN go env -w GO111MODULE=auto &&\
    go env -w GOPROXY=https://goproxy.cn,direct &&\
    go build -mod=mod main.go


EXPOSE 8080


CMD ["./main"]
