version: "3"
services:
  vtot:
    build: .
    image: vtot/golang:1.2
    container_name: "vtot"
    volumes:
      - ./tmp/:/VTOT/tmp/
      - ./config/application.yaml:/VTOT/config/application.yaml
    restart: always
    ports:
      - "18888:12333"