# 服务器端口，不写则是默认8080
server:
  port: 12333

vps: http://192.168.1.1:18888/

aliCloudSdk:
  appKey: myXjvilkzWXzvKU0
  accessKeyID: LTAI5tBsLQKQSp7x5fVPeK36
  accessKeySecret: NsQ1oRyngYtf0CeNTex91N1Nw6g3N8
